language: php

sudo: false

notifications:
  email:
    on_success: never

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer install -n

script:
  - if [[ $(phpenv version-name) == '7.2' ]]; then vendor/bin/phpunit --coverage-clover clover.xml ; fi
  - if [[ $(phpenv version-name) != '7.2' ]]; then vendor/bin/phpunit ; fi

after_script:
  - if [[ $(phpenv version-name) == '7.2' ]]; then php vendor/bin/php-coveralls -v ; fi
